### ISSUE TITLE
Working CI

### ISSUE THREAD

**Issue by pydanny** [feldroy/django-crash-starter#5]
## Description

Setup preferably with GitHub actions to work on Linux, Mac, and Windows. But we can get by on just Linux.

## Rationale

With Cookiecutters It's easy to break the build and not know about it. The answer is CI. It would be great if this could be done via GitHub actions.

## Use case(s) / visualization(s)

Add a badge so we know for certain it's working at all times.

**Comment by luzfcb** [comment]
The CI was fixed in #43, but still uses Travis-ci instead of GitHub Actions.

**Comment by pydanny** [comment]
Works for me!
